### PR TITLE
update 'Getting to new infra' blog post with links

### PR DESCRIPTION
**Pull request by larryonoff**
_Getting to new infra_ blog post updated with links into issues.

PS. I'm not sure that I added links properly.

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali/275)

### CODE REVIEW

**Comment by larryonoff** [comment]
@yaronyg please check

**Comment by yaronyg** [comment]
The links are wrong. The correct format would have been, for say issue 417, as https://github.com/thaliproject/Thali_CordovaPlugin/issues/417

And note that this is trickier than it looks as not all the issues are in the same repo. For example, issue 4 in the salti library has the URL https://github.com/thaliproject/salti/issues/4

I can't imagine this is worth the time to fix so I would suggest just abandoning this PR.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/275#-:-KR0levqCVNRm_u_kgan:b-2mysic)_

**Comment by larryonoff** [comment]
I updated links format.

I think that it's better merging this PR if format is fine, because it's better having some links broken and fix them later that just not having them. It's really difficult going thru the list of the issues without any links.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/275#-:-KR3BefSHqk7oCtPMecB:b-3ds7cf)_

**Comment by yaronyg** [comment]
You need to use absolute URIs so the link will work both on GitHub and on our website.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/275#-:-KRzraxIst4KKZfRLGJ_:bsi4pwi)_

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/275#-:-KSDjNIOrcNDRvo8GUG-:bnfp4nl)_

**Pull request merged**
