### PR TITLE
New iOS design

### PR DESCRIPTION
**Pull request by yaronyg**
Everything we thought we knew about MPCF in iOS has turned out to be wrong. This is an attempt to provide a design based on what we have learned.

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali/274)

### CODE REVIEW

**Comment by yaronyg** [comment]
@baydet Make sure to grab me on Monday and we should walk through the text together. I'm going to ask you to please explain to me what you think the text means and I'll then answer questions.

**Comment by baydet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[pages/documentation/PresenceProtocolBindings.md, line 311 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOdHpbv8ikPpBgtCUSe:-KOdHpbv8ikPpBgtCUSf:bijyyaj) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L311)):_

> HTTP endpoint

this link forwards to 404

---

_[pages/documentation/PresenceProtocolBindings.md, line 357 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOdvuuYov0HmrBkJ9nE:-KOdvuuYov0HmrBkJ9nF:b-5dlz81) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L357)):_

> but if it wishes to do so without hiding all of its identity

What is the cases when advertiser want to hide its identity? How advertiser will know that it should create completely new UUID

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/274)_

**Comment by baydet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[pages/documentation/PresenceProtocolBindings.md, line 354 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOeDWSF9GMA02QvrA2u:-KOeDWSF9GMA02QvrA2v:b-xm6zw1) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L354)):_

> ``` Markdown
> ; UUID is defined in [RFC 4122](https://tools.ietf.org/html/rfc4122)
> Generation = 1*HexidecimalDigit
> HexidecimalDigit = 0-9 / A-F
> ```

NB: /Hexidecimal/Hexadecimal

---

_[pages/documentation/PresenceProtocolBindings.md, line 357 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOeCzg36EEsXuFk2KTb:-KOeCzg4HASli_z5mXvG:btb4a33) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L357)):_

> ``` Markdown
> ```
> 
> Whenever a Thali app is told to start advertising it MUST generate a new UUID for its MCPeerID (and this UUID MUST be generated separately from the UUID used with the service browser to make sure that the two UUIDs are different, this prevents state issues with having multiple MCSessions between the same two peers). It MUST also start its generation counter at 0. If the peer wishes to notify the peers around it that it has a new value but if it wishes to do so without hiding all of its identity then what it can do is start a new MCNearbyServiceAdvertiser object with a new MCPeerID that consists of the same UUID as the previous MCNearbyServiceAdvertiser but with the generation incremented by 1. Note that the generation value MUST be a string encoding a hexidecimal representation of the counter. This will let remote peers recognize that this is the same peer they have seen before but with new data. This trick is used to make it easier for peers to preferentially look for data from known remote peers.
> 
> ```
> ```

NB: /hexidecimal/hexadecimal

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/274)_

**Comment by yaronyg** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[pages/documentation/PresenceProtocolBindings.md, line 311 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOdHpbv8ikPpBgtCUSe:-KOgWCTjg696OU25iFEd:b-fsg7j0) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L311)):_
<details><summary>

<i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>



> > HTTP endpoint
> 
> this link forwards to 404
> </details>
> Trying to fix

---

_[pages/documentation/PresenceProtocolBindings.md, line 354 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOeDWSF9GMA02QvrA2u:-KOgWBUkhZX_QrwqiQP7:b-8agds0) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L354)):_
<details><summary>

<i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>



> NB: /Hexidecimal/Hexadecimal
> </details>
> D'oh!

---

_[pages/documentation/PresenceProtocolBindings.md, line 357 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOeCzg36EEsXuFk2KTb:-KOgWKgePpFrqfe5PmL9:b-8agds0) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L357)):_
<details><summary>

<i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>



> NB: /hexidecimal/hexadecimal
> </details>
> D'oh!

---

_[pages/documentation/PresenceProtocolBindings.md, line 357 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOdvuuYov0HmrBkJ9nE:-KOgWLahEHS2ywogavSZ:b-rfjlrp) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L357)):_
<details><summary>

<i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>



> > but if it wishes to do so without hiding all of its identity
> > What is the cases when advertiser want to hide its identity? How advertiser will know that it should create completely new UUID
> > </details>
> > Check the new text. It tries to answer the question.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/274)_

**Comment by baydet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[pages/documentation/PresenceProtocolBindings.md, line 357 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOdvuuYov0HmrBkJ9nE:-KOiSfH0PfTnEJ_G1fO1:b-qp6cys) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L357)):_
Cool. Explanation below seems to be fine.
But I would like to leave previous statement 

> if it wishes to do so without hiding all of its identity

because it was straighter than the new one. The new is kind of slippery because of words "slightly more trackable". For my engineer brain it is hard to understand what logic stands for "slightly more"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/274)_

**Comment by baydet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[pages/documentation/PresenceProtocolBindings.md, line 357 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/274#-KOdvuuYov0HmrBkJ9nE:-KOnd81vakJpqbPhdBzO:b32wtd) ([raw file](https://github.com/thaliproject/thali/blob/e88ad4b4701294b4f7f02b0a9798464170354853/pages/documentation/PresenceProtocolBindings.md#L357)):_
<details><summary>

<i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>



> Cool. Explanation below seems to be fine.
> But I would like to leave previous statement 
> 
> > if it wishes to do so without hiding all of its identity
> > because it was straighter than the new one. The new is kind of slippery because of words "slightly more trackable". For my engineer brain it is hard to understand what logic stands for "slightly more"
> > </details>
> > ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/274)_

**Comment by baydet** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali/274#-:-KOndMRUOxOcWJbzVUv-:bnfp4nl)_

**Pull request merged**
