### PR TITLE
Notification doc review request

### PR DESCRIPTION
**Pull request by yaronyg**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali/224)

### CODE REVIEW

**Comment by yaronyg** [comment]
This is the work for https://github.com/thaliproject/Thali_CordovaPlugin/issues/168

**Comment by yaronyg** [comment]
@tobybrad - Please skim the text until you reach the TLS section [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md#transfering-from-notification-beacon-to-tls). Then please carefully read the [TLS Section](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md#transfering-from-notification-beacon-to-tls) and put any comments in using reviewable.io.

**Comment by yaronyg** [comment]
@DrJukka - Please skim the text until [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md#ble-binding) and then read that section carefully and please provide feedback using reviewable.io.

**Comment by yaronyg** [comment]
@tobybrad & @DrJukka - The presence protocol file was just getting stupid big so I split it into two parts. [The base spec](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md) is something you both should at least skim so you have a basic idea of what's going on.

I then @tobybrad to give a full review of the section starting [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#transfering-from-notification-beacon-to-tls). It's hard to tell because of how the titles are formatted but that section stops [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#transfering-discovery-beacon-values-over-http)

@DrJukka I need you to skim until [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#denial-of-service-dos-protections-for-discovery-and-connectivity) (the part that @tobybrad is reviewing) and then I need you to read hard starting at the previous link through the end of the BLE section.

Thanks!

**Comment by yaronyg** [comment]
@mpodwysocki - BTW, if you have any questions or comments as you read through [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md) then the reviewable link off this PR is a great place to put them so we can get them resolved.

**Comment by yaronyg** [comment]
@tobybrad - And now I would like to add a second, separate, review request. The previous request was for the section on how to bind to TLS. This new request is for the section on the multi-peer connectivity framework available [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#multi-peer-connectivity-framework-mpcf). The goal is to define a simple but complete protocol. The goal is not to arbitrarily change the existing code. So if I define something in there that changes things from the existing code in a way that is not useful then file a complaint in reviewable and I'll fix it. We aren't here to create make work and the existing code should take precedence over the spec.

**Comment by yaronyg** [comment]
@vjrantal - Please review [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#local-wi-fi-binding) but you should make sure to at least scan the spec and probably scan [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md) as well. Please use reviewable to leave comments and questions.

**Comment by DrJukka** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[presenceprotocolBindings.md, line 145 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K27ateXM0Ly0a-9qNiP)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L145)):</sup>
So, does that mean that we would need to implement some kind of protocol on checking that all bytes are getting copied over the Non-TCP connection, and if it determines any issues, it MUST disconnect all communications ?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/224)

**Comment by tobybrad** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[presenceprotocolBindings.md, line 164 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E1GqsLWQ0aHdBGFB7)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L164)):</sup>
The first trick is likely unworkable due to an expected limit on the number of MCSessions (which we can assume a) keep the radio on b) utilise some bandwidth even when idle).

The second trick.. peerID is not transmittable except during the initial handshake i.e. I couldn't just serialised a peerID onto a stream, for instance, since the interesting bits are opaque to user code. We could potentially cache the peerID we receive on invitation/discovery though it's not proved this is reusable over long periods (but no reason to assume it doesn't).



---

<sup>**[presenceprotocolBindings.md, line 331 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E3GCFhr4oJZd98ubS)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L331)):</sup>
I think we've established that it's not. At least it's not when connection go in each direction. We have workarounds.. and they appear to hold.. but throughput is likely to be non-optimal. Neither have we established that a further layer of multiplexing will show better results, mind.



---

<sup>**[presenceprotocolBindings.md, line 333 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E3rS9sOZMNJyk7Xw_)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L333)):</sup>
This is proven to be safe.



---

<sup>**[presenceprotocolBindings.md, line 346 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E46HkPTiiWff7onIX)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L346)):</sup>
UUID != MCSessionID. We need to be careful about this distinction and we need to prove that we can serialise and store and MCPeerID and then 'rehydrate' a connection from it. 



---

<sup>**[presenceprotocolBindings.md, line 387 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E5nE0VNUqipgkYOXd)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L387)):</sup>
There appears to be an existing 30 second timer in the framework that kills a session if it's not connected in time.



---

<sup>**[presenceprotocolBindings.md, line 389 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E64xFeT22J8SSuZEr)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L389)):</sup>
Browsers cant connect to peers unless they have first (perhaps time-shifted by some large value) discovered the peer. Advertisers similarly can't connect unless they've been invited by a browser. So I'm not sure the possibility of an 'unexpected' connection exists unless you have access to private API and can generate MCPeerID's at will.



---

<sup>**[presenceprotocolBindings.md, line 407 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E6pMgKX40WWrPRBaS)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L407)):</sup>
Turns our thowing away the advertiser object a lot causes crashes. (Framework has a callback in-flight at the moment you unref the object.. boom !!). Need to find a general solution to this frustrating objective-c problem.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/224)

**Comment by tobybrad** [comment]
Reviewed 2 of 3 files at r7, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/224)

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[presenceprotocolBindings.md, line 145 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K27ateXM0Ly0a-9qNiP)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L145)):</sup>
I don't think so. The reason is that TCP/IP, Bluetooth and Multiplexer all have message size checks. So if data gets lost there are at least three places in the stack where this will be detected.



---

<sup>**[presenceprotocolBindings.md, line 164 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E1GqsLWQ0aHdBGFB7)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L164)):</sup>
Do you expect a total limit on MCSessions even if there is exactly 1 MCSession with any particular peer? In other words, if I discover 1000 peers and establish 1000 MCSession's (e.g. one and only one MCSession per peer) would iOS have a heart attack even if we only actively use say 1-3 of those sessions at a time?

If it is o.k. with a 1000 MCSessions then I don't think the battery draw should be much since the sessions are only open while the app is in the foreground and I doubt they require much of anything to stay active. But that is just a guess.

As for the second trick, I thought that info is transmitted during discovery? So if it's legal to issue two simultaneous MCNearbyServiceAdvertiser objects with different `myPeerID` values one of which has an `info` object that isn't empty and contains the `myPeerID` value from the other MCNearbyServiceAdvertiser object then shouldn't all the listeners get that info and understand what is being transmitted?

Please see below for my question on using peerIDs we magically know about out of band.



---

<sup>**[presenceprotocolBindings.md, line 331 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E3GCFhr4oJZd98ubS)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L331)):</sup>
This text is outdated because of that. As for bandwidth, that is something we absolutely have to test. But given how TCP/IP works and if we are running on WiFi then the results shouldn't be too bad versus having two separate connections. Bluetooth could be another story. But we need to test.



---

<sup>**[presenceprotocolBindings.md, line 333 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E3rS9sOZMNJyk7Xw_)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L333)):</sup>
Updated in spec



---

<sup>**[presenceprotocolBindings.md, line 346 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E46HkPTiiWff7onIX)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L346)):</sup>
In this case UUID == PeerID. In other words if we use a rotating PeerID system to signal when there are state changes then if a peer comes out of background advertising the same PeerID it had when it went into background then anyone who saw that PeerID before will know that nothing had changed (because if it had, the app would have changed its PeerID). They would still have to establish a new MCSession if someone wanted to talk to the PeerID. But we know we can keep advertising the same PeerID since it's just an argument to `MCNearbyServiceAdvertiser`.



---

<sup>**[presenceprotocolBindings.md, line 387 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E5nE0VNUqipgkYOXd)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L387)):</sup>
Do you have a test to confirm that? I just want to make sure we know what these timers are so that we can bubble up the consequences through the stack.



---

<sup>**[presenceprotocolBindings.md, line 389 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E64xFeT22J8SSuZEr)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L389)):</sup>
So what happens if we call initWithDisplayName on MCPeerID using a UUID that we magically happen to know that some other peer is using and then pass that into initWithPeer on MCSession? I would expect the system would use Bonjour to look for that peerID value and connect us, thus giving us session:peer:didChangeState with MCSessionStateConnected. Am I completely off base?



---

<sup>**[presenceprotocolBindings.md, line 407 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E6pMgKX40WWrPRBaS)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/presenceprotocolBindings.md#L407)):</sup>
What happens if we call stopAdvertisingPeer but keep the object around until we go into the background?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/224)

**Comment by tobybrad** [comment]
Reviewed 2 of 6 files at r15, 2 of 2 files at r16.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 387 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E5nE0VNUqipgkYOXd)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L387)):</sup>
No test, plenty of logs that suggest it.



---

<sup>**[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 389 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E64xFeT22J8SSuZEr)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L389)):</sup>
You'd have to work hard to engineer such a situation. Sure.. it's theoretically possible if you're handy with a void \* but using the API as published.. nope.

The display name you pass into the MCPeerID ctor is just that, for display purposes only. It's not significant to the lower transport (a TXT record I think). 



---

<sup>**[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 407 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E6pMgKX40WWrPRBaS)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L407)):</sup>
Until the main loop idles is the more attractive way to do this I think. This is a general problem with all delegates called back by the framework and I'm astounded the the iOS community isn't hopping up and down or full of solutions.... but then these things only tend to surface when you thrash the objects and people don't tend to do that kind of thing.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/224)

**Comment by yaronyg** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 389 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E64xFeT22J8SSuZEr)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L389)):</sup>
Please see the new text.



---

<sup>**[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 407 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E6pMgKX40WWrPRBaS)** ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L407)):</sup>
BTW we shouldn't bang our heads against iOS. If iOS really wants us to create a single `MCNearbyServiceAdvertiser` and just use it until we go in the background then we should do that. We can force people to discover beacon changes via polling. It's not the best solution but it's more important that iOS have reliable behavior than we have the most efficient implementation. What is your advice? Should we change the binding to mandate polling or are we o.k. creating lots and lots of `MCNearbyServiceAdvertiser` objects, one for each time we need to change a notification beacon (which can be frequently if there are lots of folks around). Please advise.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/224)

**Comment by yaronyg** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 145 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K27ateXM0Ly0a-9qNiP:-K4U7cYsVKOaUWzDIhN1:-499146009) ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L145)):_
Done.

---

_[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 164 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E1GqsLWQ0aHdBGFB7:-K4U7ePZ31nQdkCHu6qi:-499146009) ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L164)):_
Done.

---

_[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 331 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E3GCFhr4oJZd98ubS:-K4U7ficNV4i9WOr1NQh:-499146009) ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L331)):_
Done.

---

_[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 333 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E3rS9sOZMNJyk7Xw_:-K4U7gA6IVitIuQ0Q765:-499146009) ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L333)):_
Done.

---

_[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 346 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E46HkPTiiWff7onIX:-K4U7hAA6jOf7SxR4gS6:-499146009) ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L346)):_
Done.

---

_[pages/TechnologyInvestigations/PresenceProtocolBindings.md, line 389 [r13]](https://reviewable.io:443/reviews/thaliproject/thali/224#-K2E64xFeT22J8SSuZEr:-K4U7iBmn5NgUcIhOJNR:-499146009) ([raw file](https://github.com/thaliproject/thali/blob/64bc154a0b744b24a2898468748752c6b3d4676b/pages/TechnologyInvestigations/PresenceProtocolBindings.md#L389)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/224)_

**Pull request merged**
