### PR TITLE
Fixed md lists - resolves #253

### LINKED ISSUE #253: Why don't lists render properly on our website?
http://thaliproject.org/Info/ scroll down to How? and notice that none of the bulleted lists are rendering as bulleted lists. What's going on?

### PR DESCRIPTION
**Pull request by deadlyfingers**
Fix for redcarpet markdown list formatting.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali/258)

### CODE REVIEW

**Comment by mpodwysocki** [comment]
_[_config.yml, line 48 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/258#-K9bobcMt5AQWwd2cGYe:-K9bobcNcQHj_8Kvmhiy:-1887298709) ([raw file](https://github.com/thaliproject/thali/blob/06849eac3d002ec76bc43869511e08d9a9ee30fe/_config.yml#L48)):_
As Yaron has mentioned we should switch over to the other project. I don't know if it'll do it for us or we have to

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/258)_

**Comment by mpodwysocki** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/258)_

**Comment by deadlyfingers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[_config.yml, line 48 [r1]](https://reviewable.io:443/reviews/thaliproject/thali/258#-K9bobcMt5AQWwd2cGYe:-K9bpCdl2JpBQnSFtqZB:-1469641292) ([raw file](https://github.com/thaliproject/thali/blob/06849eac3d002ec76bc43869511e08d9a9ee30fe/_config.yml#L48)):_
I think we have to switch it - I'll try changing to config to use kramdown instead then...
https://github.com/thaliproject/thali/issues/257

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/258)_

**Comment by deadlyfingers** [comment]
@mattpodwysocki ok, updated config to use kramdown instead of redcarpet and it seems to look the same on localhost. TOC still works and I've added a regex script to do the strikethrough effect on our stories.md as kramdown doesn't appear to support that option yet.

**Comment by mpodwysocki** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali/258)_

**Pull request merged**
