### PR TITLE
Undo the gradle multi-module refactor

### PR DESCRIPTION
**Pull request by yaronyg**
Jason had an awesome idea to refactor us into gradle modules. This made dependency management easier and it also made using IntelliJ much easier since you could open all of Production in a single project window! It was a great change. Unfortunately it surfaced two bugs that we didn't find during normal testing.

The first bug had to do with the POMs being generated in Maven having the wrong ID and version. But that was trivial to fix.

The second bug is in IntelliJ and basically IntelliJ does not handle gradle subprojects in v13 correctly. They had a regression and according to http://youtrack.jetbrains.com/issue/IDEA-120939#comment=27-777233 they don't plan to fix it. I tried their work around but it didn't work. The issue is that when running in IntelliJ the resources directory for modules aren't properly added to the path and so resources aren't found during execution. Since we need those resources that was a show stopper.

IntelliJ says to go to v14 but v14 is an EAP and not even a beta yet (by their own warning language) and anyway uses a newer version of Android that isn't compatible with our version and we don't want to upgrade right now. So we had to lose a good chunk of productivity by the whole team while we pulled out the changes. Sigh.

### CODE REVIEW

**Comment by jmspring** [comment]
Changes to java files as part of the refactor?  Just curious...

-j

**Comment by yaronyg** [comment]
I checked. Those changes were just moves. Jason had cleaned up some messy file locations which unfortunately got undone with the revert.

Is everything working?

**Comment by jmspring** [comment]
Mostly.

Moving along at the moment getting some code written.

-j

**Comment by jmspring** [comment]
Going for a bike ride, but in the process of wiring up the thread to do the replicating.

Just need to figure out the replication API for this stuff -- ie is it fire and forget, or do I need to track things.  But after bike ride I will dig in more.

-j

**Comment by yaronyg** [comment]
Given that the only thing you can do if a replication fails is retry there doesn't seem much point in tracking it. Eventually we'll want to track in order to calculate priority but not today.

Sent from my HTC

----- Reply message -----

**Comment by jmspring** [comment]
Back and working on writing a javascript test now.  Will see how this goes.
 Goal would be a pull request either tomorrow, or more likely first thing
Monday.  I"m flexible there, but we should probably chat before the PR.

-jim

**Comment by yaronyg** [comment]
If you want to chat today just let me know by email.

Sent from my HTC

----- Reply message -----

**Pull request merged**
